### ISSUE TITLE
Implement swagger docs object using swagger zod

### ISSUE THREAD

**Issue by JamieCurnow** [JamieCurnow/expree#2]

**Comment by kensington133** [comment]
Start off in /src/types/index and type up the definition to be able to call it like this ish

```ts
const def: RouteDefinition = {
  swagger: (zod) => ({
    body: zod.whatever,
    params: zod.whatever,
    query: zod.whatever
  })
}
```

Look in /src/createRoutes and add an option for the swagger stuff - like the url to put the docs at, maybe some base objecty swagger stuff - top level name and version etc. `CreateRoutesOption`

In `parseRouteHandlers` at the end before we return we need to figure out the swagger stuff for this endpoint. I think we’ll make a swagger-zod object outside of the for loop in `createRoutes` then pass that in to `parseRoutehandlers` , check if the route has a swagger key and if it does parse out that swagger key like we do with validation and put the resulting object into the global swagger object.

<img width="2553" alt="image" src="https://user-images.githubusercontent.com/2436270/180459132-bc6c00c4-25b8-4f57-be82-78bb3d9aa4db.png">
